Add modal with list of related entities
datalens-tech/datalens-ui pull request #1133
Opened 2024-06-17 12:57 UTC by mournfulCoroner

2024-06-17 13:01 UTC, mournfulCoroner commented
Related to https://github.com/datalens-tech/datalens/issues/81

2024-06-20 16:17 UTC, flops requested changes

2024-06-20 16:17 UTC, flops commented on src/ui/components/DialogRelatedEntities/DialogRelatedEntities.tsx
> +        if (!relations || isEmpty(relations) || isError) {
I think better to separate this if like this and move this logic right after isLoading check

```
if (isError) {
 return (
    <div className={b('error-state')}>
      <PlaceholderIllustration direction="column" name={'error'} title={i18n('label_request-error')} />
    </div>
 )
}
```

And `!relations  || isEmpty(relations)` when relations is [] | null is `isEmpty(relations)` (`isEmpty(null) -> true`)

In that case maybe:

```
if (isEmpty(relations)) {
   if (entry.scope === EntryScope.Widget &&
            Object.values(EDITOR_TYPE).includes(entry.type) &&
            currentDirection === Direction.Parent) { return <Alert/> }
  

  return (<div className={b('empty-state')}/>)
}
```

2024-06-20 16:17 UTC, flops commented on src/ui/components/DialogRelatedEntities/EntitiesList/EntitiesList.tsx
> +            return i18n('label_scope-chart');
`label_scope-other`

2024-06-21 09:00 UTC, flops approved these changes

2024-06-21 09:01 UTC, merged