Charts 9962 dash components refactoting
datalens-tech/datalens-ui pull request #1263
Opened 2024-07-17 07:46 UTC by mournfulCoroner

2024-07-17 15:26 UTC, Marginy605 requested changes

2024-07-17 15:26 UTC, Marginy605 commented on src/ui/libs/DatalensChartkit/modules/data-provider/charts/index.ts
> +        const path = isEmbeddedEntry() ? '/embeds/api/run' : '/api/run';
Let's get this from DL.some_const

2024-07-17 15:26 UTC, Marginy605 commented on src/ui/units/dash/containers/Body/Body.tsx
> +          noEdit?: boolean;
editable or enableEdit or onlyView would be better

2024-07-17 15:26 UTC, Marginy605 commented on src/ui/units/dash/containers/Body/Body.tsx
> +    noState?: boolean;
enableState would be better

2024-07-17 15:26 UTC, Marginy605 commented on src/ui/units/dash/store/actions/base/actions.ts
> +                applyChartkitSettings({data});
let's rename chartkit to dataproviderchart or something like this

2024-07-17 15:26 UTC, Marginy605 commented on src/ui/units/dash/store/actions/dashTyped.ts
> +        entryId?: string | null;
may be it's better use null in action?

2024-07-18 12:04 UTC, flops commented on src/ui/units/dash/hooks/useIframeFeatures.tsx
> +            if (wrapRef.current) {
resizeObserver.disconnect()

2024-07-18 12:33 UTC, flops approved these changes

2024-07-18 13:08 UTC, Marginy605 submitted a review, later dismissed

2024-07-18 14:00 UTC, flops approved these changes

2024-07-18 14:01 UTC, merged