Add metrika actions
datalens-tech/datalens-ui pull request #1400
Opened 2024-08-22 13:42 UTC by stpavlenko

2024-08-22 16:36 UTC, Marginy605 submitted a review, later dismissed

2024-08-27 11:24 UTC, flops requested changes

2024-08-27 11:24 UTC, flops commented on src/ui/units/workbooks/components/DeleteEntryDialog/DeleteEntryDialog.tsx
> +            if (data.scope === EntryScope.Connection) {
Let's move this to `deleteEntry` action itself

2024-08-29 13:20 UTC, flops approved these changes

2024-08-30 08:40 UTC, merged