Add anchor to titles on dash
datalens-tech/datalens-ui pull request #1784
Opened 2024-11-06 11:58 UTC by mournfulCoroner

2024-11-12 10:35 UTC, flops requested changes

2024-11-12 10:35 UTC, flops commented on src/ui/components/DashKit/plugins/Title/Title.tsx
> +                const contentHeight = contentRef.current.getBoundingClientRect().height || 0;
`.current.getBoundingClientRect()` - let's save this calculations once and use their values as vars.

2024-11-12 10:35 UTC, flops commented on src/ui/components/DashKit/plugins/mixins.scss
> +    background-color: var(--g-color-base-generic-ultralight);
Let's try `background: linear-gradient` ?

2024-11-12 10:35 UTC, flops commented on src/ui/units/dash/utils/scrollUtils.ts
> +                scrollIntoView(hash.replace('#', ''));
Why are we resetting hash here?

2024-11-13 13:19 UTC, mournfulCoroner commented on src/ui/components/DashKit/plugins/RendererWrapper/RendererWrapper.tsx
> +                        [String(classMod)]: Boolean(classMod),
if `classMod` is `undefined`, Boolean(classMod) will be false and classMod won't be applied

2024-11-29 09:08 UTC, mournfulCoroner commented on tests/data/us-e2e-data
Disable loadingOnlyVisibleCharts setting on screenshots dash (after adding `loadedItemsMap.size === this.props.tabData?.items.length` in isLoaded condition the loading of the mobile dash was broken)

2024-11-29 13:48 UTC, flops requested changes

2024-11-29 13:48 UTC, flops commented on src/ui/components/DashKit/DashKit.ts
> +                getTitlePlugin(options?.disableHashNavigation),
Let's use `setSettings` like in other plugins

2024-12-02 14:39 UTC, flops requested changes

2024-12-02 14:39 UTC, flops commented on src/ui/components/DashKit/plugins/Title/AnchorLink/AnchorLink.tsx
> +        <React.Fragment>
Fragment is redundant here

2024-12-02 14:39 UTC, flops commented on src/ui/components/DashKit/plugins/mixins.scss
> +        color-mix(in sRGB, var(--g-color-base-generic-ultralight) 95%, transparent),
`color-mix` arrived in support in 2023... and not supported in WebView do we really has no other options?

2024-12-02 14:57 UTC, flops requested changes

2024-12-02 14:57 UTC, flops commented on src/ui/components/DashKit/plugins/Title/Title.tsx
> +            window.addEventListener('resize', debouncedCalculateAnchor);
Do we need this handler if `showAnchor === false` ?

2024-12-03 10:05 UTC, flops approved these changes

2024-12-03 10:47 UTC, merged