Migrate entries to workbook by copy
datalens-tech/datalens-ui pull request #203
Opened 2023-11-15 15:18 UTC by Sergey-weber

Added new dialog SelectMigrationToWorkbookDialog - for selecting migration entries by copy or transfer
Modify MigrateToWorkbookDialog
Added new handler for migration entries by copy

2023-11-15 18:37 UTC, Sergey-weber commented
Тикет на документаторов - https://st.yandex-team.ru/YCDOCS-12857

2023-11-23 20:22 UTC, imsitnikov requested changes

2023-11-23 20:22 UTC, imsitnikov commented on src/ui/components/SelectMigrationToWorkbookDialog/SelectMigrationToWorkbookDialog.tsx
> +const b = block('dl-select-migration-to-workbook-dialog ');
Remove space plz

2023-11-23 20:22 UTC, imsitnikov commented on src/ui/components/MigrateToWorkbookDialog/MigrateToWorkbookDialog.scss
> -    &__error-block {
These styles are needed

2023-11-23 20:22 UTC, imsitnikov commented on src/ui/components/MigrateToWorkbookDialog/MigrateToWorkbookDialog.tsx
> +import {getRelations} from 'ui/store/actions/copyEntriesToWorkbook';
Would be better not to use actions and selectors from another store. The `copyEntriesToWorkbook` store was created for copying entries between workbooks dialog. Can we duplicate `getRelations` and selectors to `migrationToWorkbook` store?

2023-11-27 17:10 UTC, Sergey-weber commented on src/ui/components/SelectMigrationToWorkbookDialog/constants.tsx
> +            text: i18n('list_first_item_copy'),
realised key storage in constants, and in the component getting texts using these keys

2023-11-28 12:42 UTC, imsitnikov approved these changes

2023-11-29 16:37 UTC, merged