Fix chart dialog styles
datalens-tech/datalens-ui pull request #53
Opened 2023-10-11 12:37 UTC by korvin89

<details>
<summary>Before</summary>

![image](https://github.com/datalens-tech/datalens-ui/assets/26501073/7b0c3a9d-0008-4902-9643-3a36d0defa80)

</details>
<details>
<summary>After</summary>

![image](https://github.com/datalens-tech/datalens-ui/assets/26501073/76732e37-15b6-4ce5-bfad-ba8e013fab93)

</details>

[CHARTS-8363]

2023-10-11 12:55 UTC, Marginy605 requested changes

2023-10-11 12:55 UTC, Marginy605 commented on src/ui/units/dash/containers/DropdownNavigation/DropdownNavigation.js
> +                    {/* <Icon
Let's remove commented code

2023-10-11 12:55 UTC, Marginy605 commented on src/ui/units/dash/components/NavigationInput/NavigationInput.scss
> +        width: fit-content;
Button changes it's width after click on "Specify link" below. Looks weird.

2023-10-11 15:12 UTC, mournfulCoroner commented
![2023-10-11_17-33-29](https://github.com/datalens-tech/datalens-ui/assets/56549651/3716907d-e41f-4d79-87b1-6a12ea435d00)
![2023-10-11_17-33-02](https://github.com/datalens-tech/datalens-ui/assets/56549651/62327e7d-00c3-4c1c-99d3-aa760756d165)
This is a rare user case, but could it be better to stretch the width of these two buttons?


<details>
<summary>Example</summary>

![image](https://github.com/datalens-tech/datalens-ui/assets/56549651/bbad3d0f-974b-4042-ba75-cdb36bbb0533)

![image](https://github.com/datalens-tech/datalens-ui/assets/56549651/4bb984df-0032-4abc-b907-15266d7ff9be)

</details>

2023-10-11 16:22 UTC, korvin89 commented
> ![2023-10-11_17-33-29](https://user-images.githubusercontent.com/56549651/274322302-3716907d-e41f-4d79-87b1-6a12ea435d00.png) ![2023-10-11_17-33-02](https://user-images.githubusercontent.com/56549651/274322346-62327e7d-00c3-4c1c-99d3-aa760756d165.png) This is a rare user case, but could it be better to stretch the width of the "Open" button to the width of the two buttons at the bottom?
> 
> Example

I think it looks a little bit weird

2023-10-12 14:02 UTC, mournfulCoroner approved these changes

2023-10-12 14:06 UTC, Marginy605 approved these changes

2023-10-12 14:08 UTC, merged