Add basic GroupControls layout
datalens-tech/datalens-ui pull request #584
Opened 2024-02-06 14:27 UTC by mournfulCoroner

Display group selectors without support for some functions

2024-02-07 19:37 UTC, Marginy605 requested changes

2024-02-07 19:37 UTC, Marginy605 commented on src/ui/components/DashKit/plugins/GroupControl/Control/store/types.ts
> +        type: 'SET_ERROR_DATA',
Due to our agreements we decided to use Symbol and scope for action names, for ex.
Symbol('dash/SET_CONTROL_ERROR_DATA')

2024-02-08 15:00 UTC, Marginy605 approved these changes

2024-02-08 15:35 UTC, flops requested changes

2024-02-08 15:35 UTC, flops commented on src/ui/components/DashKit/plugins/Control/Control.tsx
> +                        onClickRetry={() => {
Move anonymous function as method, or this component will re-render every time it's created. 
```
onClickRetry = () => this.reload();
```
And then
```
onClickRetry={this.onClickRetry}
```

2024-02-09 11:37 UTC, flops approved these changes

2024-02-09 11:38 UTC, merged

2024-03-14 12:09 UTC, mournfulCoroner commented
Related to https://github.com/datalens-tech/datalens/issues/89