Support mobile view for AsideHeader Settings
datalens-tech/datalens-ui pull request #70
Opened 2023-10-16 14:30 UTC by mournfulCoroner

2023-10-17 09:00 UTC, Marginy605 requested changes

2023-10-18 09:00 UTC, mournfulCoroner commented on src/ui/components/AsideHeaderAdapter/Settings/LanguageSettings.tsx
> +    const getLanguageOptions = React.useCallback(
Based on a DL constant, so I pulled `languageOptions` out of the component

2023-10-18 09:01 UTC, mournfulCoroner commented on src/ui/components/MobileHeader/MobileHeaderComponent/BurgerMenuFooter/BurgerMenuFooter.tsx
> +    const onClickSettings = () => {
Decided not to use `useCallback` in this place. Prefix fixed.

2023-10-18 15:23 UTC, Marginy605 approved these changes

2023-10-18 15:23 UTC, merged