Support relations in group controls
datalens-tech/datalens-ui pull request #749
Opened 2024-03-11 13:11 UTC by mournfulCoroner

Related to https://github.com/datalens-tech/datalens/issues/89

- set up the correct operation of links in group selectors (include migration links from old selectors to new)
- add the ability to select the current item in the group selector relations dialog
- a new way of displaying debug info for group selectors
- new system for counting loaded selectors in group selectors
- change naming of subitems in groups from items to group

2024-03-14 14:08 UTC, mournfulCoroner commented on package.json
> +    "@gravity-ui/dashkit": "^6.9.0",
need fix

2024-03-14 14:15 UTC, mournfulCoroner commented on src/ui/units/dash/containers/Dialogs/DialogRelations/hooks/helpers.ts
>      // filtering logic is reproduced from old links
can be deleted

2024-03-18 11:21 UTC, Marginy605 requested changes

2024-03-18 11:21 UTC, Marginy605 commented on src/i18n-keysets/component.dialog-relations.view/en.json
> +  "label_current-selector": "Selector: ",
It's a bad practice to add space and colon inside keysets! Need to remove it and add it on usage

2024-04-04 15:37 UTC, Marginy605 requested changes

2024-04-09 11:58 UTC, flops approved these changes

2024-04-09 12:14 UTC, Marginy605 approved these changes

2024-04-09 12:20 UTC, merged