add validation error for name with slash
datalens-tech/datalens-ui pull request #77
Opened 2023-10-17 12:33 UTC by Sergey-weber

Added validation error for name  in input with slash

2023-10-17 17:10 UTC, imsitnikov requested changes

2023-10-18 09:54 UTC, Sergey-weber commented
Тикет на документаторов - https://st.yandex-team.ru/YCDOCS-12360

2023-10-30 13:31 UTC, jhoncool approved these changes

2023-10-30 13:41 UTC, imsitnikov approved these changes

2023-10-31 08:34 UTC, merged